# Generated by Django 5.2.6 on 2025-10-05 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentiComerciali',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=50, unique=True)),
                ('denumirea', models.CharField(max_length=255)),
                ('cod_fiscal', models.CharField(max_length=50)),
                ('denumirea_completa', models.CharField(blank=True, max_length=255, null=True)),
                ('conducator', models.CharField(blank=True, max_length=255, null=True)),
                ('forma_juridica', models.CharField(blank=True, max_length=100, null=True)),
                ('adresa_juridica', models.CharField(blank=True, max_length=255, null=True)),
                ('adresa_postala', models.CharField(blank=True, max_length=255, null=True)),
                ('telefoane', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('rezident', models.BooleanField(default=False)),
                ('tara', models.CharField(blank=True, max_length=100, null=True)),
                ('cod_tva', models.CharField(blank=True, max_length=50, null=True)),
                ('cont_bancar_iban', models.CharField(blank=True, max_length=34, null=True)),
                ('contract_baza', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'agenti_comerciali',
            },
        ),
        migrations.CreateModel(
            name='ContBancar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denumirea', models.CharField(max_length=255)),
                ('iban', models.CharField(max_length=34)),
                ('tip_cont', models.CharField(choices=[('lei', 'În lei'), ('valuta', 'Valută')], max_length=50)),
                ('valuta', models.CharField(blank=True, max_length=10, null=True)),
                ('banca_organizatiei', models.CharField(blank=True, max_length=255, null=True)),
                ('banca_corespondent', models.CharField(blank=True, max_length=255, null=True)),
                ('data_deschiderii', models.DateField(blank=True, null=True)),
                ('data_inchiderii', models.DateField(blank=True, null=True)),
                ('cod_fiscal_trezorerie', models.CharField(blank=True, max_length=50, null=True)),
                ('prin_trezoreria', models.CharField(blank=True, max_length=255, null=True)),
                ('denumirea_trezoreriei', models.CharField(blank=True, max_length=255, null=True)),
                ('numar_cont_trezorerie', models.CharField(blank=True, max_length=34, null=True)),
                ('decontari_directe', models.BooleanField(default=False)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conturi', to='core.agenticomerciali')),
            ],
            options={
                'db_table': 'cont_bancar',
            },
        ),
        migrations.CreateModel(
            name='Contracte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=50, unique=True)),
                ('denumirea', models.CharField(max_length=255)),
                ('institutia', models.CharField(blank=True, max_length=255, null=True)),
                ('programul', models.CharField(blank=True, max_length=255, null=True)),
                ('componente_de_sursa', models.CharField(blank=True, max_length=255, null=True)),
                ('originea_sursei', models.CharField(blank=True, max_length=255, null=True)),
                ('iban', models.CharField(blank=True, max_length=34, null=True)),
                ('eco', models.CharField(blank=True, max_length=50, null=True)),
                ('contul_de_decontare', models.CharField(blank=True, max_length=255, null=True)),
                ('nr_contractului', models.CharField(max_length=100)),
                ('data_contractului', models.DateField()),
                ('conditii_plata', models.CharField(blank=True, max_length=255, null=True)),
                ('termen_valabilitate', models.DateField(blank=True, null=True)),
                ('suma_contractului', models.DecimalField(decimal_places=2, max_digits=18)),
                ('cota_avans', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('suma_in_valuta', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('cod_obiectului', models.CharField(blank=True, max_length=100, null=True)),
                ('cod_valutei', models.CharField(blank=True, max_length=10, null=True)),
                ('continut_prescurtat', models.TextField(blank=True, null=True)),
                ('data_indeplinirii_obligatiilor', models.DateField(blank=True, null=True)),
                ('masura', models.CharField(blank=True, max_length=255, null=True)),
                ('contractul_nu_este_inregistrat_la_trezorerie', models.BooleanField(default=False)),
                ('prin_achizitii_publice', models.BooleanField(default=False)),
                ('contract_produse_alimentare', models.BooleanField(default=False)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracte', to='core.agenticomerciali')),
            ],
            options={
                'db_table': 'contracte',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numar', models.CharField(max_length=100)),
                ('data_facturii', models.DateField()),
                ('suma_facturii', models.DecimalField(decimal_places=2, max_digits=18)),
                ('valuta', models.CharField(blank=True, max_length=10, null=True)),
                ('comentariu', models.TextField(blank=True, null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturi', to='core.contracte')),
            ],
            options={
                'db_table': 'facturi',
            },
        ),
        migrations.CreateModel(
            name='FacturaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denumirea', models.CharField(max_length=255)),
                ('cantitate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pret_unitar', models.DecimalField(decimal_places=2, max_digits=12)),
                ('suma', models.DecimalField(decimal_places=2, max_digits=18)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.factura')),
            ],
            options={
                'db_table': 'factura_items',
            },
        ),
        migrations.CreateModel(
            name='Plata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_platii', models.DateField()),
                ('suma_platita', models.DecimalField(decimal_places=2, max_digits=18)),
                ('metoda', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Transfer Bancar'), ('card', 'Card'), ('other', 'Altele')], default='bank', max_length=20)),
                ('numar_document', models.CharField(max_length=100)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plati', to='core.factura')),
            ],
            options={
                'db_table': 'plati',
            },
        ),
    ]
