# Generated by Django 5.2.7 on 2025-10-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contbancar',
            name='tip_cont',
            field=models.CharField(max_length=50),
        ),
    ]
