# Generated by Django 5.2.7 on 2025-10-29 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_contbancar_tip_cont'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_bugetar', models.CharField(max_length=50, unique=True)),
                ('denumirea', models.CharField(max_length=255)),
                ('suma_alocata', models.DecimalField(decimal_places=2, max_digits=18)),
                ('anul', models.IntegerField(default=2025)),
            ],
            options={
                'db_table': 'linii_bugetare',
            },
        ),
        migrations.AddField(
            model_name='factura',
            name='budget_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturi', to='core.budgetline'),
        ),
    ]
