# Generated by Django 5.2.7 on 2025-10-29 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_budgetline_factura_budget_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaitem',
            name='budget_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='core.budgetline'),
        ),
    ]
